# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: reno
description: Somos un estudio de grabación independiente
author:
  name: Estudios Reno
  email: info@estudiosreno.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: false

permalink: none

prose:
  rooturl: 'app/_posts'
  media: 'app/images/trabajos'
  ignore:
    - estudio
  metadata:
    app/_posts/renos:
      - name: 'title'
        field:
          element: 'text'
          label: 'Nombre'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'null'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'ident'
        field:
          element: 'hidden'
          value: ''
      - name: 'hardcore'
        field:
          element: 'hidden'
          value: 'false'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'renos'

    app/_posts/trabajos:
      - name: 'title'
        field:
          element: 'text'
          label: 'Disco'
          placeholder: 'Disco'
      - name: 'artist'
        field:
          element: 'text'
          label: 'Artista'
          placeholder: 'Artista'
      - name: 'url'
        field:
          element: 'text'
          label: 'URL'
          placeholder: 'URL'
      - name: 'ident'
        field:
          element: 'text'
          label: 'Identificador'
          placeholder: 'Identificador'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'null'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'trabajos'