# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: reno
description: Somos un estudio de grabación independiente
author:
  name: Estudios Reno
  email: info@estudiosreno.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: false

permalink: none

prose:
  siteurl: 'http://prose.github.io/#descuadro/reno/'
  rooturl: 'app/_posts'
  ignore:
    - estudio

  metadata:
    "app/_posts/renos":
      - name: "category"
        field:
          element: "hidden"
          value: "reno"
      - name: "layout"
        field:
          element: "hidden"
          value: "null"
      - name: "permalink"
        field:
          element: "hidden"
          value: "/index.html"

      - name: "hardcore"
        field:
          element: "multiselect"
          label: "Hardcore?"
          options:
            - name: "Hardcore Member"
              value: "true"
            - name: "Little Tit"
              value: "false"