# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: reno
description: Somos un estudio de grabación independiente
author:
  name: Estudios Reno
  email: info@estudiosreno.com

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

pygments: false

permalink: none

# Language Defaults

#nav:
#  servicios: ""
#  estudio: ""
#  renos: ""
#  trabajo: ""
#  blog: ""
#  contacto: ""

# Prose Config

prose:
  rooturl: 'app/_posts'
  media: 'app/images/trabajos'
  ignore:
    - estudio
    - servicios
  metadata:
  #servicios
    app/_posts/en/estudio:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'slider'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'estudio'
      - name: 'title'
        field:
          element: 'text'
          label: 'Nombre'
      - name: 'language'
        field:
          element: 'text'
          label: 'Lenguaje'
      - name: 'ident'
        field:
          element: 'text'
          placeholder: 'Nombre de la imagen asociada'
      - name: 'categories'
      - name: 'slides'
        field:
          element: 'text'
          placeholder: 'Número de imágenes'

    app/_posts/es/estudio:
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'slider'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'estudio'
      - name: 'title'
        field:
          element: 'text'
          label: 'Nombre'
      - name: 'language'
        field:
          element: 'text'
          label: 'Lenguaje'
      - name: 'ident'
        field:
          element: 'text'
          placeholder: 'Nombre de la imagen asociada'
      - name: 'categories'
      - name: 'slides'
        field:
          element: 'text'
          placeholder: 'Número de imágenes'

  #renos
    app/_posts/en/renos:
      - name: 'title'
        field:
          element: 'text'
          label: 'Nombre'
      - name: 'language'
        field:
          element: 'text'
          label: 'Lenguaje'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'null'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'ident'
        field:
          element: 'hidden'
          value: ''
      - name: 'hardcore'
        field:
          element: 'hidden'
          value: 'false'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'renos'

    app/_posts/es/renos:
      - name: 'title'
        field:
          element: 'text'
          label: 'Nombre'
      - name: 'language'
        field:
          element: 'text'
          label: 'Lenguaje'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'null'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'ident'
        field:
          element: 'hidden'
          value: ''
      - name: 'hardcore'
        field:
          element: 'hidden'
          value: 'false'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'renos'

    #trabajos
    app/_posts/trabajos:
      - name: 'title'
        field:
          element: 'text'
          label: 'Disco'
          placeholder: 'Disco'
      - name: 'artist'
        field:
          element: 'text'
          label: 'Artista'
          placeholder: 'Artista'
      - name: 'url'
        field:
          element: 'text'
          label: 'URL'
          placeholder: 'URL'
      - name: 'ident'
        field:
          element: 'text'
          label: 'Identificador'
          placeholder: 'Identificador (Nombre de imagen sin extensión)'
      - name: 'layout'
        field:
          element: 'hidden'
          value: 'null'
      - name: 'permalink'
        field:
          element: 'hidden'
          value: '/index.html'
      - name: 'categories'
        field:
          element: 'hidden'
          value: 'trabajos'